name: Manually Build LLVM on Ubuntu

on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag
        required: true
        type: string

permissions:
  contents: write
  discussions: write

jobs:
  build-on-amd64:
    name: "build-on-ubuntu-22.04-amd64"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Build Script
        run: |
          set -euo pipefail
          bash build_clangd_nightly.sh  "`pwd`/llvm/"
          tar -cf llvm-amd.tar.gz llvm/bin/clangd llvm/lib/clang/

      - name: Release Artifacts to Github Release Page
        if: ${{ steps.vars.outputs.needs_build == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          tag_name: ${{ inputs.tag }}-amd
          files: |
            llvm-amd.tar.gz

  build-on-arm64:
    name: "build-on-ubuntu-22.04-arm64"
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Build Script
        run: |
          set -euo pipefail
          bash build_clangd_nightly.sh  "`pwd`/llvm/"
          tar -cf llvm-arm.tar.gz llvm/bin/clangd llvm/lib/clang/

      - name: Release Artifacts to Github Release Page
        if: ${{ steps.vars.outputs.needs_build == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          tag_name: ${{ inputs.tag }}-arm
          files: |
            llvm-arm.tar.gz


